# Generated by Django 4.2.6 on 2023-10-11 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(null=True)),
                ('barcode', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Imported', 'imported')], max_length=10)),
                ('imported_t', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=80, null=True)),
                ('quantity', models.CharField(max_length=10)),
                ('categories', models.CharField(blank=True, max_length=80, null=True)),
                ('packaging', models.CharField(blank=True, max_length=80, null=True)),
                ('brands', models.CharField(blank=True, max_length=60, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
