# Generated by Django 4.2.6 on 2023-10-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_fact', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
