# Generated by Django 4.2.6 on 2023-10-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_fact', '0003_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
