# Generated by Django 4.2.6 on 2023-11-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_fact', '0004_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_manufacture',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processed_foods',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
