# Generated by Django 4.2.6 on 2023-11-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_fact', '0005_product_country_of_manufacture_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
