# Generated by Django 4.2.6 on 2023-11-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_fact', '0007_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.CharField(blank=True, max_length=15, null=True)),
                ('fat', models.CharField(blank=True, max_length=15, null=True)),
                ('saturated_fat', models.CharField(blank=True, max_length=15, null=True)),
                ('carbohydrates', models.CharField(blank=True, max_length=15, null=True)),
                ('sugars', models.CharField(blank=True, max_length=15, null=True)),
                ('lactose', models.CharField(blank=True, max_length=15, null=True)),
                ('fiber', models.CharField(blank=True, max_length=15, null=True)),
                ('proteins', models.CharField(blank=True, max_length=15, null=True)),
                ('salt', models.CharField(blank=True, max_length=15, null=True)),
                ('alcohol', models.CharField(blank=True, max_length=15, null=True)),
                ('vitamina_a', models.CharField(blank=True, max_length=15, null=True)),
                ('vitamina_b', models.CharField(blank=True, max_length=15, null=True)),
                ('vitamina_c', models.CharField(blank=True, max_length=15, null=True)),
                ('vitamina_d', models.CharField(blank=True, max_length=15, null=True)),
                ('vitamina_e', models.CharField(blank=True, max_length=15, null=True)),
                ('calcium', models.CharField(blank=True, max_length=15, null=True)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_fact.product')),
            ],
            options={
                'verbose_name': 'Nutriente',
            },
        ),
    ]
